image: node:20

stages:
  - lint
  - deploy

# Lint - exécuté sur toutes les branches
lint_nuxt:
  stage: lint
  script:
    - npm install -g pnpm
    - python3 infrastructure/scripts/lint.nuxt.py

# Deploy DEV - uniquement sur branche dev
deploy_dev:
  stage: deploy
  needs:
    - lint_nuxt
  script:
    - npm install -g pnpm
    - apt-get update && apt-get install -y python3-pip
    - pip3 install boto3 --break-system-packages
    - python3 infrastructure/scripts/deploy.nuxt.py dev
  only:
    - dev

# Deploy PRD - uniquement sur branche main
deploy_prd:
  stage: deploy
  needs:
    - lint_nuxt
  script:
    - npm install -g pnpm
    - apt-get update && apt-get install -y python3-pip
    - pip3 install boto3 --break-system-packages
    - python3 infrastructure/scripts/deploy.nuxt.py prd
  only:
    - main
