image: node:20

stages:
  - lint
  - deploy

# Installation des dépendances communes
.setup: &setup
  - npm install -g pnpm
  - pip install boto3

# Lint - exécuté sur toutes les branches
lint_nuxt:
  stage: lint
  script:
    - npm install -g pnpm
    - python3 infrastructure/scripts/lint.nuxt.py

# Deploy DEV - uniquement sur branche dev
deploy_dev:
  stage: deploy
  needs:
    - lint_nuxt
  script:
    - *setup
    - python3 infrastructure/scripts/deploy.nuxt.py dev
  only:
    - dev

# Deploy PRD - uniquement sur branche main
deploy_prd:
  stage: deploy
  needs:
    - lint_nuxt
  script:
    - *setup
    - python3 infrastructure/scripts/deploy.nuxt.py prd
  only:
    - main
